language: c

compiler:
  - gcc

before_script:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -y
  - sudo apt-get install qemu-kvm -y
  - sudo apt-get install libxen-dev -y
  - sudo apt-get install g++-4.8 -y

env:
  - PLATFORM=xen TESTS=none EXTRAFLAGS=
  - PLATFORM=xen TESTS=none EXTRAFLAGS='-- -F ACLFLAGS=-m32'
  - PLATFORM=baremetal TESTS=qemu EXTRAFLAGS='-- -F ACLFLAGS=-m32 -F ACLFLAGS=-march=i686'

script:
  - export CC=gcc-4.8
  - export CXX=g++-4.8
  - ./build-rr.sh -qq ${PLATFORM} ${EXTRAFLAGS}
  - RUMPRUN_PLATFORM=$(echo ${PLATFORM} | sed 's/baremetal/bmk/') ./tests/buildtests.sh
  - ./tests/runtests.sh ${TESTS}

notifications:
  irc:
    channels:
      - "chat.freenode.net#rumpkernel-builds"
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
    skip_join: true
    use_notice: true
  email:
    recipients:
      - rumpkernel-builds@freelists.org
    on_success: always
    on_failure: always

# touch me to force a travis rebuild
